#!/usr/bin/env ruby  

magia = %x[git log --pretty=oneline --no-merges --author=DrummerHead --since='yesterday']

unless magia.empty?
  magia.gsub!(/^\w* /, "").gsub!(/\n/, "; ")
  puts magia
else
  puts "Gotta worky work!"
end
